service: serverless-offline-unsupported-media-type-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  environment:
    INVOKE_ENDPOINT: 'http://localhost:4000'
    INVOKE_FUNCTION: 'invokeTest'

custom:
  serverless-offline:
    port: 4000

functions:
  apiTest:
    handler: 'api-lambda.handler'
    events:
      - http:
          method: get
          path: /api

  invokeTest:
    handler: 'invoke-lambda.handler'

